### ISSUE TITLE
Have base config separate from react config

### ISSUE THREAD

**Issue by hrafne** [ueno-llc/styleguide#4]
Wanted to use this in a non-react project so the react rules wouldn't apply. Should there be a base config separate from react and jsx rules like we do with react-native config?

Something like for base:
```
"extends": "@ueno"
```
and for react
```
"extends": "@ueno/eslint-config/react"
```

**Comment by jeremybarbet** [comment]
@hrafne That should answer you question, right? https://github.com/ueno-llc/styleguide/tree/master/packages/eslint-config

**Comment by hrafne** [comment]
@JeremDsgn resolved this in a #5, forgot to close.
